### ISSUE TITLE
Usar um template personalizado

### ISSUE THREAD

**Issue by skay1994** [brunosantoshx/hxphp-docs#1]
Estou começando a estudar o MVC e escolhi seu framework pela otima proposta, porem estou montando um layout que possui um slidebar fixo com os menus, queria saber se teria como separa esse pedaço em um arquivo de template para nao precisar repetir o codigo em todos os views, ou seria somente via include?

**Comment by brunosantoshx** [comment]
Olá @skay1994, como vai? 

Sim, é perfeitamente possível utilizando as views parciais. Confira os detalhes na documentação:
https://github.com/brunosantoshx/hxphp-docs/blob/master/06-views.md

Forte abraço e sucesso sempre!
