### ISSUE TITLE
Alert (Helpers) não está passando para a index do cadastro

### ISSUE THREAD

**Issue by rigelcastro** [brunosantoshx/hxphp-docs#14]
Boa tarde pessoal,

Estou fazendo esta serie Criando Sistema de Cadastro de Login e Níveis e já cheguei a aula #5.

Cheguei a parte das Messagens de Errors, porém quando vou incluir o comando:

`<?php echo $this->alert ?>`

Para exibir o Error na index.phtml dá um FatalError:

`Fatal error: Method HXPHP\System\Helpers\Alert\Alert::__toString() must not throw an exception, caught TypeError: Return value of HXPHP\System\Helpers\Alert\Alert::getAlert() must be of the type string, null returned in C:\wamp\www\sistema\app\views\cadastro\index.phtml on line 0`

Parece que tudo está funcionando corretamente, pois quando eu incluo este comando (`echo $this->alert;`) no Controller , mostra o Alert.  Somente na index.phtml que está seguindo com este erro.

Alguém poderia me dá uma ajuda?

Obrigado,

Leonardo.

PS.: continuei com a série e o Alert na página de LOGIN está funcionando corretamente.

**Comment by brunosantoshx** [comment]
Olá @rigelcastro, tudo bem?

Valeu por relatar! Já subi um commit que resolve este problema! É que no PHP 7 temos validação por tipo de retorno e, como você não definiu nada, o retorno é do tipo `null` que conflitava com a regra de retorno do tipo `string`.

Abs

**Comment by rigelcastro** [comment]
Oi Bruno, desculpe-me mas onde está este commit ? 

Preciso da solução deste problema rsrs

**Comment by brunosantoshx** [comment]
Olá @rigelcastro, boa tarde. Tudo bem?

Aqui está:
https://github.com/brunosantoshx/hxphp/commit/8791758577ecc2eab00352b04104b0a3f11229be
