### ISSUE TITLE
Ajuda no CSS do HXPHP

### ISSUE THREAD

**Issue by rigelcastro** [brunosantoshx/hxphp-docs#16]
Boa noite galera,

Estou com muita dificuldade com o CSS deste HXPHP por ter só o básico de CSS. Nada que modifico no `bootstrap/dist/css/bootstrap.min.css` é aplicado em view. 

Simplesmente quero criar 2 div's dentro de outra (container) lado-a-lado no PANEL-BODY de uma view , mas tudo que faço resulta em nada ;-(

Alguém para me dá um help.

Leonardo.

**Comment by brunosantoshx** [comment]
Olá Leonardo, tudo bem?

Creio que você escolheu o caminho mais difícil hehehe. 

O recomendo é você editar o cabeçalho `app/views/header.phtml` e adicionar uma nova folha de estilo `public/css/estilos.css`.

Assim não tem erro! A ideia não é você seguir a estrutura do framework em tudo, mas, se sentir livre para customizar.

Abração e sucesso sempre!
