### ISSUE TITLE
TinyMCE upload image local

### ISSUE THREAD

**Issue by rigelcastro** [brunosantoshx/hxphp-docs#17]
Bom dia,

Preciso de +1 ajuda para finalizar meu mini projeto da escola utilizando o `HXPHP`. 

Basicamente este mini projeto é para alunos fazerem exercícios com perguntas de múltipla escolha, e com o sistema de login o professor terá o controle das notas.

- Fiz a integração do `TinyMCE` nos` textareas`, cuja principal finalidade é armazenar as perguntas e respostas que conterão textos e imagens.
- Criei uma `view` para o cadastro de questões e já está indo para o BD. Porém a configuração do `TinyMCE` não está 100%, pois só estão indo os textos para o BD, as imagens não.

Dei uma olhada na documentação do TinyMCE e explica o upload de imagens local. Nela descreve as funções e o funcionamento das coisas. 
Para upload de imagens locais é preciso de um arquivo chamado postAcceptor.php (coloquei-o na raiz) que fará a manipulação da imagem dentro do servidor (parece que está funcionando pois a imagem é inserida na pasta de configuração ). O problema é que se eu escrevo no `<textarea>`  uma frase e acrescento também uma imagem, infelizmente só está indo para o BD o texto sem a imagem.

Bruno, meu amigo ... help-me rsrs ... preciso tanto de um editor para formular questões com texto e imagens que estou pensando em procurar outro editor, pois este tinyMCE está tomando muito do meu tempo.

Meu formulário está assim:
```

<form action="<?php echo BASE; ?>professor/inserir/" class="form-horizontal" method="post" enctype="multipart/form-data">
                        <div class="form-group">
                          <div class="avaliacaoEnunciado">Enunciado:</div>
                          <div class="col-sm-8">
                            <textarea name="question" class="mceEnunciado form-control" id="question"></textarea>
                          </div>
                        </div>

                        <div class="form-group">
                          <div class="col-sm-offset-3 col-sm-7">
                            <button type="submit" style='width: 100%' class="btn btn-success fa fa-credit-card">  Cadastrar</button>
                          </div>
                        </div>
</form>
```

E o script do tinyMCE está assim:

```
tinymce.init({
mode : 'specific_textareas',
editor_selector : 'mceEnunciado',
  language: 'pt_BR',
  language_url: '/sistema/public/bower_components/bootstrap/js/tinymce/langs/pt_BR.js',
  height: 50,
  width: 520,

  plugins: [
      "image"
  ],

  toolbar1: "image",

  content_css: [
    '//fonts.googleapis.com/css?family=Lato:300,300i,400,400i',
    '//www.tinymce.com/css/codepen.min.css'],

  menubar: false,
  forced_root_block : false,
  image_title: true, 
  automatic_uploads: true,
  images_upload_url: '/sistema/postAcceptor.php',
  file_picker_types: 'image', 

  file_picker_callback: function(cb, value, meta) {
    var input = document.createElement('input');
    input.setAttribute('type', 'file');
    input.setAttribute('accept', 'image/*');
    
    input.onchange = function() {
      var file = this.files[0];
      
      var reader = new FileReader();
      reader.readAsDataURL(file);
      reader.onload = function () {
 
        var id = 'blobid' + (new Date()).getTime();
        var blobCache =  tinymce.activeEditor.editorUpload.blobCache;
        var base64 = reader.result.split(',')[1];
        var blobInfo = blobCache.create(id, file, base64);
        blobCache.add(blobInfo);

        cb(blobInfo.blobUri(), { title: file.name });
      };
    };
    
    input.click();
  }
});
```

Não sei mais o que fazer, será que o HXPHP bloqueia o upload de imagem pelo tinyMCE? Alguém me indicaria um editor simples que permita o usuário inserir texto e imagem num <textarea> e salvar no banco ?

[]'s.

Leonardo.

**Comment by rigelcastro** [comment]
Fiz a inclusão de um plugin muito simples e elegante chamado JustBoil.me Images (http://justboil.me/) específico para tinyMCE (a imagens estão sendo guardadas na pasta ok). 

Estou com uma leve suspeita que o post() do HXPHP não está passando as imagens. Será?

**Comment by rigelcastro** [comment]
Bom dia Bruno,

Precisava saber se o HXPHP tem ou não suporte para editores de textos. Já implementei com o tinyMCE e o CKEditor, mas nenhum deles salva o texto formatado no banco (inclusive as imagens).

[]'s

Leonardo

**Comment by rigelcastro** [comment]
Bom dia,

Para aqueles que visitarem algum dia este comentário, comunico que "resolvi" o problema.

A solução mais fácil que encontrei foi usar na **Action** do meu **Controller** a boa e velha variável global `$_POST[]` ao invés do `post()` do HXPHP (mesmo sabendo que não é segura, porém meu sistema é pessoal e para amigos).

Não posso afirmar com toda certeza, mas parece que o método `$view->request->post()` (Request.php) filtra as **TAGs** e outros. Pois dei uma olhada no Request.php e verifiquei que existe um **FILTER** na passagem do post. 
Essas TAGs são absolutamente necessárias para a formatação de textos e o funcionamento dos outros plugins (**table, image, list, etc**), que compõem o **TinyMCE**, **CKEditor** e outros editores de textos wysiwyg.
Ou seja, é preciso que o Bruno ou colaboradores modifiquem este método ou mesmo crie um outro para usar em `form's`

Espero ajudar com esta informação.

**Comment by brunosantoshx** [comment]
Olá @rigelcastro, bom dia. Tudo bem?

Perdoe pela demora em lhe responder! Estou em uma correria insana em uma startup que está com apenas 60 dias de existência.

Sobre sua dúvida: Permitir códigos HTML, por padrão, seria um erro crítico de segurança, afinal, esta é a base mais simples de ataques XSS. É possível receber códigos HTML nos métodos do objeto `Request` selecionando um filtro que não trata tags, porém, tome cuidado! Se este campo está disponível para qualquer usuário (não é o dono do projeto e admin) você pode ter sérios problemas! Portanto, busque ferramentas para proteção contra XSS, se for este o caso.

Para habilitar no HXPHP:
```php
$this->request->setCustomFilters(array(
			'google_maps' => FILTER_UNSAFE_RAW
		));
```

Abração e sucesso sempre!
