### ISSUE TITLE
Erro nas datas do sistema 

### ISSUE THREAD

**Issue by sfatuche** [brunosantoshx/hxphp-docs#19]
configurei a principio tudo conforme o tutorial mas fica ainda essa msg de erro e não consegui corrigir...

Warning: Declaration of ActiveRecord\DateTime::setTime($hour, $minute, $second = 0) should be compatible with DateTime::setTime($hour, $minute, $second = NULL, $microseconds = NULL) in /Applications/MAMP/htdocs/sistema/vendor/php-activerecord/php-activerecord/lib/DateTime.php on line 36

Agora qual devo usar para que sejam iguais??? Na verdade não estou encontrando a declaração de ActiveRecord

**Comment by rigelcastro** [comment]
Bom dia,

Eu tive um problema de incompatibilidade com DateTime (achei a solução, mas não a encontrei agora para lhe guiar). 
Acredito que esteja faltando um parâmetro na declaração do seu método `$microseconds = null`.

Tente acrescentar este parâmetro para ver ser funfa, ou aguarde o Bruno vir responder rs

setTime($hour, $minute, $second = NULL, `$microseconds = NULL`)

**Comment by sfatuche** [comment]
Perfeito era isso mesmo...

Na linha 168 do arquivo referido no erro

###estava assim###

public function setTime($hour, $minute, $second =0)
{
$this->flag_dirty();
return parent::setTime($hour, $minute, $second);
}

###ficou assim###

public function setTime($hour, $minute, $second = null, $microseconds = NULL)
	{
		$this->flag_dirty();
		return parent::setTime($hour, $minute, $second);
	}

Mas fica uma duvida essa data vem de onde?
É a data do PHP, ou do Servido.

Obrigado pela dica, estou respondendo para que ajude se mais alguém tiver o mesmo problema
