### ISSUE TITLE
Conexão em sqlite

### ISSUE THREAD

**Issue by Kyareshi** [brunosantoshx/hxphp-docs#2]
Eu preciso fazer uma conexão em um banco de dados sqlite, como eu poderia fazer isso?

**Comment by brunosantoshx** [comment]
Olá @Kyareshi, como vai?

Você só precisa alterar o parâmetro `driver` no `app/config.php`:
https://github.com/brunosantoshx/hxphp-docs/blob/master/02-installation-and-configuration.md

Forte abraço e sucesso sempre!

**Comment by brunosantoshx** [comment]
Aqui tem todas as especificações detalhadas: http://www.phpactiverecord.org/docs/ActiveRecord/Connection

**Comment by Kyareshi** [comment]
Opa @brunosantoshx, valeu... mas eu to tendo esse erro aqui:

` Fatal error: Uncaught exception 'ActiveRecord\DatabaseException' with message 'Could not find sqlite db: sqlite//C:/Users/Kyareshi/Desktop/Developing/Database.db/' in C:\wamp64\www\sistema\vendor\php-activerecord\php-activerecord\lib\adapters\SqliteAdapter.php on line 22`
A conexão que eu fiz foi:

> 'driver' => 'sqlite',
> 'host' => 'sqlite://C:/Users/Kyareshi/Desktop/Developing/Database.db'
