### ISSUE TITLE
Erro Alert

### ISSUE THREAD

**Issue by giovanidomingues** [brunosantoshx/hxphp-docs#20]
Nao consigo resolver esse problema, 

Notice: Undefined property: HXPHP\System\View::$alert in C:\xampp1\htdocs\creditrans\app\views\cadastro\index.phtml on line 11 

grato

**Comment by giovanidomingues** [comment]
está dando esse erro em editar perfil 

Fatal error: Uncaught Error: Class 'Form' not found in C:\xampp1\htdocs\creditrans\app\views\perfil\editar.phtml:12 Stack trace: #0 C:\xampp1\htdocs\creditrans\src\HXPHP\System\View.php(288): require_once() #1 C:\xampp1\htdocs\creditrans\src\HXPHP\System\App.php(112): HXPHP\System\View->flush() #2 C:\xampp1\htdocs\creditrans\index.php(36): HXPHP\System\App->run() #3 {main} thrown in C:\xampp1\htdocs\creditrans\app\views\perfil\editar.phtml on line 12

e esse

Warning: Invalid argument supplied for foreach() in C:\xampp1\htdocs\creditrans\src\HXPHP\System\Http\Request.php on line 143

como resolvo?

**Comment by giovanidomingues** [comment]
NBa verdade reinstalei o hxphp resolveu o de cima mas ainda dá esse erro

Warning: Invalid argument supplied for foreach() in C:\xampp1\htdocs\creditrans\src\HXPHP\System\Http\Request.php on line 143

grato

**Comment by rigelcastro** [comment]
Boa noite, 

Vc instalou o pacote da class Form pelo composer ?

Vc não precisa seguir o video do Bruno com este recurso. Se vc usar o formulário html também vai funcionar. Tente fazer dessa maneira.

**Comment by giovanidomingues** [comment]
me diz uma coisa nao tem como colocar todas as funcoes numa pasta? tipo ali foi criado usuario, ai no views eu tive que criar uma pasta usuarios, uma cadastro, uma perfil, etc.... nao tem como deixar tudo numa mesma pasta? pq se eu precisar criar por exemplo clientes, ai o cadastro de cliente, alteração, listar, etc.... como eu faria? ou a regra é essa mesma criar tudo em pastas de acordo com o controller?

grato

**Comment by celsonguila** [comment]
saudações Giovani

Deixa ver tentar explicar a sua duvida

Pode sim criar vários controllers e direccionar para mesma pasta, mas ten de forçar o controller e encaminhar os pedidos das views para aquela pasta ex:

$this->view
                        ->setPath('user') // Aqui é onde deve colocar o nome da pasta onde está a view que quer aceder
                        ->setFile('my-entities')  // aqui é o nome da view que quer aceder
                        ->setVars([
                            'user_obj' => $usr // por fim as variáveis a entregar nas views
                          
                ]);

Não sei se consegui entender e explicar a sua dúvida.

Por exemplo pode criar UsuariosController, CadastroController, PerfilController e direccionar todos esses controllers para  ->setPath('user')  e todas views desses controllers encaminhados para essa pasta.

**Comment by giovanidomingues** [comment]
tem algum email, whatsapp etc... que posso falar com vc?

**Comment by celsonguila** [comment]
e-mail : celsoluisnguila@gmail.com  whatsapp : +258844110716

**Comment by Davidsonc** [comment]
Tambem estou com os mesmos dois erros, alguem sabe porque isso esta acontecendo ? 

( ! ) Warning: Invalid argument supplied for foreach() in C:\xampp\htdocs\sistema\src\HXPHP\System\Http\Request.php on line 143
Call Stack
#	Time	Memory	Function	Location
1	0.4052	363760	{main}( )	...\index.php:0
2	0.4668	1490840	HXPHP\System\App->run( )	...\index.php:52
3	0.4985	1872704	call_user_func_array:{C:\xampp\htdocs\sistema\src\HXPHP\System\App.php:107} ( )	...\App.php:107
4	0.4985	1872760	PerfilController->editarAction( )	...\App.php:107
5	0.4985	1872688	HXPHP\System\Http\Request->post( )	...\PerfilController.php:41


e esse



( ! ) Fatal error: Uncaught Error: Class 'Form' not found in C:\xampp\htdocs\sistema\app\views\perfil\editar.phtml on line 12
--
1 | 0.4052 | 363760 | {main}( ) | ...\index.php:0
2 | 0.4668 | 1490840 | HXPHP\System\App->run( ) | ...\index.php:52
3 | 0.4998 | 1872360 | HXPHP\System\View->flush( ) | ...\App.php:112
4 | 0.5011 | 1882472 | require_once( 'C:\xampp\htdocs\sistema\app\views\perfil\editar.phtml') | ...\View.php:290





Alguém sabe resolver ?
