### ISSUE TITLE
Alterar Framework Bootstrap

### ISSUE THREAD

**Issue by Julianojc** [brunosantoshx/hxphp-docs#4]
Olá Bruno, tudo bem..estou acompanhando seus videos em seu canal youtube, e em um deles vc diz que o HXPHP vem com o Bootstrap como padrão, é possível alterar este framework para o material design lite por exemplo?..quais seriam os passos?

**Comment by junio-gon** [comment]
É possível sim, insira nas regras CSS - se não me engano na pasta /public/css/ - do seu novo template, depois defina o que ficará no header, footer, e ainda o que vai para cada index de cada view.

**Comment by brunosantoshx** [comment]
Olá @Julianojc, como vai?

O @junio-gon está correto! É perfeitamente possível alterar o framework padrão do HXPHP e para isso só é necessário alterar os estilos inseridos no header.

Forte abraço e sucesso sempre!
