### ISSUE TITLE
gerar relatorios

### ISSUE THREAD

**Issue by anthonycrhistian** [brunosantoshx/hxphp-docs#5]
Boa tarde Bruno, estou utilizando o HXPHP para meu TCC, e surgiu uma duvida, como posso integrar um modulo que gere relatórios, como o Reportico para Yii, teria como eu usar esse? tentarei adaptar para meu uso, fiquei em duvida de adiciono como modulo ou serviço,

**Comment by brunosantoshx** [comment]
Olá @anthonycrhistian, como vai?

Curti bastante a ideia e acredito que pode se tornar um módulo bem útil, portanto gostaria de lhe perguntar de antemão. Você tem interesse em publicar no Github o resultado final para que outros usuários também possam utilizar?

Eu nunca trabalhei com este módulo, portanto não posso assegurar a compatibilidade para uma leve adaptação, mas posso lhe ajudar com sua dúvida sobre o HXPHP:

A ideia do Serviço é um único arquivo com uma única responsabilidade. Já o módulo é composto por vários arquivos (cada um para uma responsabilidade específica) e que desempenha múltiplas responsabilidades.

Espero ter ajudado.
Forte abraço e sucesso sempre!

**Comment by anthonycrhistian** [comment]
muito obrigado ajudou sim, estava com essa duvida de serviços e modulos, caso eu consiga adaptar o modulo do reportico para o Yii, postarei sim o resultado., agradeço por toda ajuda!

**Comment by anthonycrhistian** [comment]
Olá bruno tudo bem? reabrindo aqui, estou com uma duvida de como criar um modulo para relatorios usando a biblioteca FPDF, na documentação não tem, eu registrei o modulo, coloquei os arquivos na pasta HXPHP\System\Modules\Fpdf, no controle de relatorios usei $this->load('Modules\Fpdf');
        $relatorio = $this->gerarFpdf->gerar($tabela);
mas, dá o seguinte erro
Fatal error: Uncaught exception 'Exception' with message 'Parametro <gerarFpdf> nao encontrado.' in C:\xampp\htdocs\SistemaTI\src\HXPHP\System\Controller.php:130 Stack trace: #0 C:\xampp\htdocs\SistemaTI\app\controllers\RelatorioController.php(51): HXPHP\System\Controller->__get('gerarFpdf') #1 [internal function]: RelatorioController->gerarAction() #2 C:\xampp\htdocs\SistemaTI\src\HXPHP\System\App.php(103): call_user_func_array(Array, Array) #3 C:\xampp\htdocs\SistemaTI\index.php(36): HXPHP\System\App->run() #4 {main} thrown in C:\xampp\htdocs\SistemaTI\src\HXPHP\System\Controller.php on line 130

como posso fazer com ele envie corretamente os dados para o modulo fpdf que gera o relatorio em pdf, que já esta ok, testei sem ser um modulo no hxphp, desde já agradeço

**Comment by brunosantoshx** [comment]
Olá @anthonycrhistian, como vai?

O método load injeta o módulo no padrão lowercase. Portanto, o correto seria `$this->fpdf->gerar($tabela);`
