### ISSUE TITLE
erro Auth quando acessado o sistema pela rede(ip da maquina)

### ISSUE THREAD

**Issue by anthonycrhistian** [brunosantoshx/hxphp-docs#6]
acontece o seguinte erro ao tentar acessar pelo ip da maquina(preciso para a rede local acessar o sistema)
Fatal error: Uncaught exception 'Exception' with message 'Verifique as configuracoes de autenticacao para a subpasta: < default >' in C:\xampp\htdocs\SistemaTI\src\HXPHP\System\Services\Auth\Auth.php:47 Stack trace: #0 [internal function]: HXPHP\System\Services\Auth\Auth->__construct(NULL, NULL, true) 
#1 C:\xampp\htdocs\SistemaTI\src\HXPHP\System\Controller.php(106): ReflectionClass->newInstanceArgs(Array) 
#2 C:\xampp\htdocs\SistemaTI\app\controllers\LoginController.php(9): HXPHP\System\Controller->load('Services\\Auth', NULL, NULL, true) 
#3 C:\xampp\htdocs\SistemaTI\src\HXPHP\System\App.php(90): LoginController->__construct(Object(HXPHP\System\Configs\Config)) 
#4 C:\xampp\htdocs\SistemaTI\index.php(36): HXPHP\System\App->run()
 #5 {main} thrown in C:\xampp\htdocs\SistemaTI\src\HXPHP\System\Services\Auth\Auth.php on line 47

ate se eu tentar na própria maquina http://192.168.0.102/sistemati/login dá o erro, se eu acessar http://localhost/sistemati/login entra normal

**Comment by brunosantoshx** [comment]
Olá @anthonycrhistian, como vai?

Isto é bem simples. O ambiente de desenvolvimento não contém este IP definido, portanto o HXPHP irá entender que é um ambiente de produção e buscar pelas suas respectivas configurações.

Você deve ter configurado exclusivamente para desenvolvimento. Para resolver você pode adicionar o IP ao ambiente de desenvolvimento ou adicionar as configurações de produção.

Forte abraço e sucesso sempre!

**Comment by anthonycrhistian** [comment]
vou bem, e espero que você também esteja bem, muito obrigado pela ajuda, realmente não tinha visto que o constructor do ambiente tinha a lista de servers, estava olhando só para o exemplo da documentação hehe. muito obrigado mesmo!!!!
