### ISSUE TITLE
Visitar perfil de outro usuário.

### ISSUE THREAD

**Issue by Kyareshi** [brunosantoshx/hxphp-docs#7]
Estou fazendo um painel usando o hxphp, e queria saber como eu faria para poder visitar o perfil de outro usuário.

**Comment by brunosantoshx** [comment]
Olá @Kyareshi, como vai?

Isto é bem simples, na verdade, porém requer alguns cuidados. Você vai precisar retirar as verificações de nível de acesso do controller para que se torne público e também terá que tomar cuidado com a segurança.

Algumas dicas:
+ Crie um controller específico para listar apenas os dados dos perfis, isto é, métodos de editar, salvar e etc devem estar em outro controller;
+ Na obtenção dos dados só solicite do banco o que é realmente necessário, isto é, no parâmetro de configuração `select` do PHP Activerecord liste apenas os campos que serão necessários e deixe de lado os campos password, salt e etc;
+ Você não precisa se limitar apenas ao uso da ID do usuário como parâmetro de identificação, isto é, se puder gerar um slug será mais relevante para SEO.

Acho que é isso.
Forte abraço e sucesso sempre!
