### ISSUE TITLE
Alterar o caminho das pastas controllers

### ISSUE THREAD

**Issue by celsonguila** [brunosantoshx/hxphp-docs#8]
Saudações Bruno
As videos aulas são muito boas e verifiquei o hxphp e é um espectáculo, no entanto preciso saber se consigo alterar o caminho das minhas pastas controller, model e view ?

Ex. gostaria que ficasse assim 

htxphp ->app ->modules -> e dentro desta estarem as pastas (controller, model e view).

A ideia é organizar as pastas dos controlers,model e view em cada módulos.

Abraços

**Comment by brunosantoshx** [comment]
Olá @celsonguila, tudo bem?

Claro! Está na documentação:
https://github.com/brunosantoshx/hxphp-docs/blob/master/02-installation-and-configuration.md

```php
$configs = new HXPHP\System\Configs\Config;

  //Globais
  $configs->global->models->directory = APP_PATH . 'models' . DS;

  $configs->global->views->directory = APP_PATH . 'views' . DS;
  $configs->global->views->extension = '.phtml';

  $configs->global->controllers->directory = APP_PATH . 'controllers' . DS;
  $configs->global->controllers->notFound = 'Error404Controller';
```

Espero ter te ajudado.
Forte abraço e sucesso sempre!
