### ISSUE TITLE
Gerar Relatórios com MPDF

### ISSUE THREAD

**Issue by thiagomnobre** [brunosantoshx/hxphp-docs#9]
Olá bruno.
Estou tentando criar um módulo para gerar relatórios mas não sei como fazer.
no caso estou tentando usar o mpdf.
Copiei a pasta do mpdf para dentro da pasta Modules.
Criei o arquivo pdf.php dentro de Configs/Modules
Registrei o módulo pdf no arquivo RegisterModules.php.
Mas não estou sabendo como usar esse módulo.

**Comment by brunosantoshx** [comment]
Olá @thiagomnobre, tudo bem?

A criação de módulos é bem simples, porém alguns cuidados devem ser tomados e acredito que principalmente com `namespaces`. Esta não é a única alternativa para o uso de outras ferramentas dentro do HXPHP, você pode simplesmente instalar através do `composer` e usar livremente como precisar. 

Forte abraço e sucesso sempre!
